# Generated by Django 5.2 on 2025-04-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="feedback",
            field=models.TextField(blank=True),
        ),
    ]
