# Generated by Django 5.1.6 on 2025-02-28 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_healthgoal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="calorie",
            new_name="calories",
        ),
    ]
